"""SQL update

Revision ID: 22adff55188d
Revises: beeba7b7750a
Create Date: 2021-08-19 00:18:45.534473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22adff55188d'
down_revision = 'beeba7b7750a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###
