"""empty message

Revision ID: 3e17db9f5182
Revises: 7576e8e3e4e9
Create Date: 2021-08-23 09:13:12.264340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e17db9f5182'
down_revision = '7576e8e3e4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog_category')
    # ### end Alembic commands ###
