"""DB schema update

Revision ID: 5e633192c84c
Revises: ebb863498e7c
Create Date: 2021-08-20 07:37:30.974249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e633192c84c'
down_revision = 'ebb863498e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_subscriber_email'), 'subscribers', ['subscriber_email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_subscriber_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
