"""update db

Revision ID: 7576e8e3e4e9
Revises: 5e633192c84c
Create Date: 2021-08-21 12:41:36.483400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7576e8e3e4e9'
down_revision = '5e633192c84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog_image')
    # ### end Alembic commands ###
